import "./globals.css";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import { Header } from "@/components/Header/Header";
const inter = Inter({ subsets: ["latin"] });
import { NextThemeProvider } from '@/components/ThemeProvider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <NextThemeProvider>
          <Theme appearance="light" accentColor="violet" panelBackground="solid">
            <Header />
            {children}
          </Theme>
        </NextThemeProvider>
      </body>
    </html>
  );
}
